[project]
name = "pdf-dashboard-with-mcp"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "streamlit[pdf]",
    "langchain",
    "langchain-chroma",
    "ollama",
    "langchain-ollama",
    "langchain-text-splitters",
    "pillow",
    "PyMuPDF",
    "langchain-community",
    "langchain-pymupdf4llm",
    "mcp[cli]",
]

[tool.uv]
exclude-newer = "5 days"
constraint-dependencies = [
    "requests>=2.33.0",
    "langchain-core>=1.2.11",
]
